### ISSUE TITLE
大佬 api可以分享一下吗

### ISSUE THREAD

**Issue by modifyFun** [caoyangim/Eyepetizer_kotlin#1]
想用api 来做下练习 如果可以的话分享一份 感激不尽 mail：www524563@qq.com

**Comment by caoyangim** [comment]
地址是:http://baobab.kaiyanapp.com/
具体请求路径可在我的MainPageService.kt文件下查看。

https://github.com/caoyangim/Eyepetizer_kotlin/blob/master/app/src/main/java/com/cy/eyepetizer/logic/network/api/MainPageService.kt
